# Generated by Django 5.2 on 2025-04-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_message_date_alter_message_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('quantity', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
